---
title: "Application: Stardew Valley Community Center Completion Times"
author: "Jared Cummings"
date: "Winter 2022"
output: pdf_document
---

**Add code to answer the following questions. Answer them in order. Knit your R markdown file. Submit your R markdown file and knitted PDF on LearningSuite by the start of class on January 11th.**

```{r, setup_and_data, echo = FALSE, message = FALSE}
library(tidyverse)
stardew <- read_csv('stardew_valley.csv', skip=1)
```

#### 1. What is the population we are trying to learn about by using this data?\newline
Answer goes here

#### 2. What is the sample size of the data?\newline
Answer goes here

#### 3. What is the random variable for the Stardew Valley data? What are the units?\newline
Answer goes here

#### 4. From looking at the data, what is a reasonable sample space? Defend your answer.\newline
Answer goes here

#### 5. R has functions for doing many simple calculations. One of these is the "mean" function. It is used the same as the "unique" function. What is the mean community center completion time of the data?\newline
Answer goes here

#### 6. Is the value you computed in (5) a parameter or a statistic? Defend your answer.\newline
Answer goes here
